name: ViperKits
main: ViperKits\ViperKits
version: 0.1.0_beta
author: jasonwynn10
api: [3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.1]
softdepend: ["EconomyAPI", "PocketMoney"]
permissions:
 ViperKits:
  default: op
  children:
   ViperKits.use:
    default: op
   battlekits.listkits:
    default: true
   ViperKits.sign:
    default: op
    children:
     ViperKits.sign.use:
      default: true
     ViperKits.sign.create:
      default: op
