name: InfinityStone
author: "jasonwynn10"
version: 0.1.0
api: [3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.1]
main: jasonwynn10\iStone\Main
description: "The stone that will never break"
commands:
  infinity:
    usage: "/infinity"
    permission: infinity.cmd 
    description: "makes the next stone block mined by that player immortal"
permissions:
  infinity.cmd:
    default: op
